version: '3.9'

services:
  web:
    build:
      context: .
    container_name: web
    command: /app/entrypoint.sh gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://root:secret@db:5432/learndashdb
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=learndashdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  staticfiles:
  media:
