# Generated by Django 4.2.18 on 2025-01-15 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashUserGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
            options={
                "db_table": "dash_users_groups",
            },
        ),
        migrations.CreateModel(
            name="DashUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("instructor", "Instructor"),
                            ("admin", "Admin"),
                        ],
                        default="student",
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dashuser_set",
                        through="users.DashUserGroups",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "db_table": "dash_users",
            },
        ),
        migrations.CreateModel(
            name="DashUserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.dashusermodel",
                    ),
                ),
            ],
            options={
                "db_table": "dash_users_permissions",
            },
        ),
        migrations.AddField(
            model_name="dashusermodel",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="dashuser_set",
                through="users.DashUserPermissions",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="dashusergroups",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.dashusermodel"
            ),
        ),
    ]
