# Generated by Django 4.2.18 on 2025-01-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashusermodel",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="dashusermodel",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="dashusermodel",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="dashusermodel",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="dashusermodel",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="dashusermodel",
            name="username",
        ),
    ]
