# Generated by Django 4.2.18 on 2025-01-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_dashusermodel_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashusermodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
