# Generated by Django 4.2.18 on 2025-01-18 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemodel",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="users.dashusermodel",
            ),
        ),
        migrations.AddIndex(
            model_name="coursecategorymodel",
            index=models.Index(
                fields=["deleted_at"], name="course_cate_deleted_7700c3_idx"
            ),
        ),
        migrations.AddField(
            model_name="answermodel",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="courses.quizmodel",
            ),
        ),
        migrations.AddIndex(
            model_name="quizmodel",
            index=models.Index(
                fields=["deleted_at"], name="quizzes_deleted_6d5d2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionmodel",
            index=models.Index(
                fields=["deleted_at"], name="questions_deleted_5be6be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonsmodel",
            index=models.Index(
                fields=["deleted_at"], name="lessons_deleted_a6ff6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursemodel",
            index=models.Index(
                fields=["deleted_at"], name="courses_deleted_18331f_idx"
            ),
        ),
    ]
